import { launch, shot, sleep } from './harness.mjs';
// Opens the auction page, bids, buys now, lists a vehicle, and checks the economy stays consistent.
const { page, close, logs } = await launch({ width: 1440, height: 810 });
await page.waitForFunction(() => window.__app && window.__app.mode === 'play', null, { timeout: 240000 });
const res = await page.evaluate(async () => {
  const a = window.__app, A = a.auction, out = {};
  a.profile.money = 400000; a.profile.level = 30;
  a.openMenu('auction');
  await new Promise((r) => setTimeout(r, 700));
  out.listings = A.listings.length;
  const l = A.live('buy')[0];
  out.first = `${l.def.name} start ${l.start} high ${l.high} bids ${l.bids}`;
  out.bid = A.bid(l, A.min(l));
  out.held = A.held;
  out.badBid = A.bid(A.live('buy')[1], 1);
  const cheap = A.live('buy').sort((x, y) => x.buyNow - y.buyNow)[0];
  const before = a.profile.garage.vehicles.length, money = a.profile.money;
  out.buyNow = A.buyNow(cheap);
  out.garage = [before, a.profile.garage.vehicles.length];
  out.paid = money - a.profile.money; out.buyNowPrice = cheap.buyNow;
  A.now = l.endsAt - 0.5;
  for (let i = 0; i < 40; i++) A.update(0.1);
  out.after = `${l.state} ${l.bidder} ${l.high}`;
  out.garage2 = a.profile.garage.vehicles.length;
  out.heldAfter = A.held;
  return out;
});
console.log(JSON.stringify(res, null, 1));
await sleep(600);
console.log(await shot(page, 'auction_buy'));
const sell = await page.evaluate(async () => {
  const a = window.__app, A = a.auction, out = {};
  const p = a.profile, v = p.garage.vehicles.find((x) => x.uid !== p.garage.selected);
  out.list = A.list(v.uid, { id: 'quick', label: 'Quick sale', secs: 60, reserve: 0.7 });
  out.selectedBlocked = A.list(p.garage.selected, { id: 'quick', label: 'Quick sale', secs: 60, reserve: 0.7 });
  a.menu.go('auction', { tab: 'sell', force: true });
  await new Promise((r) => setTimeout(r, 500));
  const l = A.live('sell')[0];
  for (let i = 0; i < 600 && !(l.bidder && l.high >= l.reserve); i++) A.update(0.25);
  out.state = `${l.state} high ${l.high} reserve ${l.reserve} bids ${l.bids}`;
  await new Promise((r) => setTimeout(r, 600));
  const m0 = p.money;
  out.accept = A.accept(l);
  out.gain = p.money - m0; out.expect = Math.round(l.high * 0.92);
  out.vehicles = p.garage.vehicles.length;
  return out;
});
console.log(JSON.stringify(sell, null, 1));
await sleep(500);
console.log(await shot(page, 'auction_sell'));
await page.evaluate(() => window.__app.menu.go('auction', { tab: 'log', force: true }));
await sleep(500);
console.log(await shot(page, 'auction_log'));
console.log('logs:', logs.filter((l) => !/getImageData/.test(l)).slice(0, 6).join('\n') || 'none');
await close(); process.exit(0);
