import { chromium } from 'playwright-core';
import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path';
const ROOT = path.resolve('.');
const server = http.createServer((req, res) => { const f = path.join(ROOT, decodeURIComponent(req.url.split('?')[0])); if (!fs.existsSync(f) || fs.statSync(f).isDirectory()) { res.writeHead(404); return res.end(); } res.writeHead(200, { 'Content-Type': f.endsWith('.html') ? 'text/html' : 'text/javascript' }); res.end(fs.readFileSync(f)); }).listen(0);
const port = server.address().port;
const browser = await chromium.launch({ channel: 'msedge', headless: true, args: ['--enable-gpu', '--ignore-gpu-blocklist', '--use-angle=d3d11'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
page.on('pageerror', (e) => console.error('ERR', e.message));
await page.goto(`http://127.0.0.1:${port}/tools/pages/bench.html`);
await page.waitForFunction(() => window.ready);
const run = async (label, kind, tris, opts) => { const r = await page.evaluate(([k, t, o]) => window.setup(k, t, o), [kind, tris, opts]); const ms = await page.evaluate(() => window.gpu()); console.log(label.padEnd(44), 'tris', String(r.tris).padStart(8), 'gpu', ms, 'ms'); };
const runD = async (label, kind, count, tris) => { await page.evaluate(([k, c, t]) => window.setupDraws(k, c, t), [kind, count, tris]); const ms = await page.evaluate(() => window.gpu()); console.log(label.padEnd(44), 'gpu', ms, 'ms'); };
await runD('1 batched instance', 'batchedBig', 1, 4000);
await runD('200 separate meshes x 20 tris', 'meshes', 200, 20);
await runD('500 separate meshes x 20 tris', 'meshes', 500, 20);
await runD('1000 separate meshes x 20 tris', 'meshes', 1000, 20);
await runD('200 batched ranges x 20 tris', 'batched', 200, 20);
await runD('500 batched ranges x 20 tris', 'batched', 500, 20);
await runD('1000 batched ranges x 20 tris', 'batched', 1000, 20);
await runD('1000 batched ranges x 200 tris', 'batched', 1000, 200);
await runD('1 mesh 200k tris', 'batchedBig', 1, 200000);
await browser.close(); server.close(); process.exit(0);
