import fs from 'node:fs';
import { launch } from './harness.mjs';
const { page, close, logs } = await launch({ width: 960, height: 540 });
await page.waitForFunction(() => window.__game && window.__game.player?.vehicle, null, { timeout: 240000 });
const out = await page.evaluate(async () => {
  window.__pauseLoop = true;
  const g = window.__game, P = g.player, sea = g.world.sea, THREE = window.__THREE;
  g.traffic.update = () => {}; g.peds.update = () => {}; g.seaTraffic.update = () => {};
  g.sky.timeScale = 0; g.sky.lockWeather = 'sunny'; g.sky.setWeather('sunny', true); g.sky.time = 12;
  P.exit?.(); P.hidden = false; P.vehicle = null; P.seq = null;
  P.x = -1140; P.z = 340; P.y = sea.waveAt(P.x, P.z) - 1.08; P.state = 'swim';
  for (let i = 0; i < 120; i++) g.update(1 / 30);
  const res = {};
  const sc = g.marine.schools.filter((q) => q.active && q.key === 'sardine')[0];
  res.sc = sc ? { n: sc.fish.length, c: [sc.cx, sc.cy, sc.cz].map((v) => +v.toFixed(1)), f0: [sc.fish[0].x, sc.fish[0].y, sc.fish[0].z].map((v) => +v.toFixed(1)), sc0: sc.fish[0].sc } : null;
  const m = g.marine.meshes.sardine; res.count = m.count; res.vis = m.visible; res.mat = m.material.type;
  res.m0 = Array.from(m.instanceMatrix.array.slice(0, 16)).map((v) => +v.toFixed(2));
  res.prog = g.renderer.info.programs.length;
  g.rig.cinematic({ from: new THREE.Vector3(sc.cx - 6, sc.cy + 0.2, sc.cz), target: new THREE.Vector3(sc.cx, sc.cy, sc.cz), dur: 99, snap: 100 });
  for (let i = 0; i < 8; i++) g.update(1 / 30);
  res.cam = g.camera.position.toArray().map((v) => +v.toFixed(1)); res.under = sea.under;
  res.inView = sc.fish.filter((f) => g.view.sphere(f.x, f.y, f.z, 1)).length;
  g.render(1 / 60);
  res.drawn = m.count; res.shot = g.canvas.toDataURL('image/jpeg', 0.9);
  return res;
});
fs.writeFileSync('data/shots/dbgfish.jpg', Buffer.from(out.shot.split(',')[1], 'base64')); delete out.shot;
console.log(JSON.stringify(out));
console.log(logs.slice(0, 10).join('\n') || 'no errors');
await close();
