import { launch, shot, sleep } from './harness.mjs';
const { page, close, logs } = await launch({ width: 1280, height: 720 });
await page.waitForFunction(() => window.__app && window.__app.mode === 'play', null, { timeout: 240000 });
await page.evaluate(() => { const g = window.__game; g.sky.time = 11; g.sky.lockWeather = 'sunny'; g.sky.setWeather('sunny', true); });
await page.keyboard.down('KeyW');
await sleep(4500);
await page.keyboard.down('KeyD'); await sleep(900); await page.keyboard.up('KeyD');
await sleep(1500);
await page.keyboard.up('KeyW');
await page.keyboard.press('F3');
await sleep(3500);
console.log('mode', await page.evaluate(() => window.__app.mode), 'len', await page.evaluate(() => window.__app.replay.length.toFixed(1)));
console.log(await shot(page, 'replay_ui1'));
await page.keyboard.press('Space'); await page.keyboard.press('ArrowRight'); await page.keyboard.press('Digit3');
await sleep(800);
console.log(await shot(page, 'replay_ui2'));
console.log('state', await page.evaluate(() => { const R = window.__app.replay; return JSON.stringify({ paused: R.paused, t: R.t.toFixed(2), shot: R.shot }); }));
await page.keyboard.press('Escape');
await sleep(2200);
console.log('mode after', await page.evaluate(() => window.__app.mode));
console.log('logs:', logs.filter((l) => !/getImageData/.test(l)).slice(0, 8).join('\n') || 'none');
await close(); process.exit(0);
