import { launch } from './harness.mjs';
import fs from 'node:fs';
const { page, close, logs } = await launch({ width: 1280, height: 720 });
await page.waitForFunction(() => window.__game && window.__game.player?.vehicle, null, { timeout: 240000 });
fs.mkdirSync('data/shots', { recursive: true });
const out = await page.evaluate(async () => {
  window.__pauseLoop = true;
  const g = window.__game, P = g.player, I = g.input, sea = g.world.sea, res = { log: [], shots: [] };
  g.traffic.update = () => {}; g.peds.update = () => {}; g.seaTraffic.update = () => {};
  g.sky.timeScale = 0; g.sky.lockWeather = 'sunny'; g.sky.setWeather('sunny', true); g.sky.time = 12;
  g.pipeline.setQuality({ scale: 1, samples: 2, bloom: true });
  P.exit?.(); P.hidden = false; P.vehicle = null; P.seq = null;
  const X = -1500, Z = 100;
  P.x = X; P.z = Z; P.y = sea.waveAt(X, Z) - 1.08; P.state = 'swim'; P.yaw = -1.57; g.rig.footYaw = -1.57; g.rig.footPitch = 0.15;
  res.depthBed = +(-2.2 - g.world.terrain.height(X, Z)).toFixed(1);
  const key = (c, on) => { if (on) { I.down.add(c); } else I.down.delete(c); };
  const step = (n) => { for (let i = 0; i < n; i++) g.update(1 / 60); };
  const snap = (label) => { g.render(1 / 60); res.shots.push(g.canvas.toDataURL('image/jpeg', 0.88)); res.log.push(label + ' y=' + (P.y - sea.waveAt(P.x, P.z)).toFixed(2) + ' dive=' + P.dive.toFixed(2) + ' o2=' + P.o2.toFixed(2) + ' spd=' + P.speed.toFixed(2) + ' under=' + sea.under); };
  step(90); snap('surface');
  key('KeyW', true); step(60); res.log.push('speed after 1s ' + P.speed.toFixed(2)); step(120); res.log.push('speed after 3s ' + P.speed.toFixed(2));
  key('KeyW', false); step(40); res.log.push('speed 0.7s after release ' + P.speed.toFixed(2));
  key('KeyW', true); key('ControlLeft', true); step(150); snap('diving 2.5s');
  step(120); snap('diving 4.5s');
  key('ControlLeft', false); key('KeyW', false); step(240); snap('drifting up');
  key('Space', true); step(180); key('Space', false); snap('after rise');
  key('ControlLeft', true); step(60 * 70); key('ControlLeft', false); snap('70s hold');
  return res;
});
out.shots.forEach((u, i) => fs.writeFileSync(`data/shots/swim_${i}.jpg`, Buffer.from(u.split(',')[1], 'base64')));
console.log(out.depthBed, out.log.join('\n'));
console.log(logs.filter((l) => !/getImageData/.test(l)).slice(0, 10).join('\n') || 'no errors');
await close();
