import { launch } from './harness.mjs';
import fs from 'node:fs';
const { page, close, logs } = await launch({ width: 1280, height: 720 });
await page.waitForFunction(() => window.__game && window.__game.player?.vehicle, null, { timeout: 240000 });
fs.mkdirSync('data/shots', { recursive: true });
const url = await page.evaluate(async () => {
  window.__pauseLoop = true;
  const g = window.__game, P = g.player, I = g.input;
  g.traffic.update = () => {}; g.peds.update = () => {};
  g.pipeline.setQuality({ scale: 1, samples: 2, bloom: true });
  g.sky.time = 14; g.sky.timeScale = 0; g.sky.lockWeather = 'sunny'; g.sky.setWeather('sunny', true);
  const boat = g.yard.slots.find((s) => s.id === 'sport').v;
  P.exit?.(); P.hidden = false; P.vehicle = null; P.state = 'foot'; P.seq = null;
  boat.place(-1500, 0, 100, 1.2); boat.moor = null; boat.phys.engineOn = true;
  P.enter(boat);
  g.world.sea.waves.settle(5, g.sky.wind.dir);
  I.down.add('KeyW');
  for (let i = 0; i < 60 * 14; i++) g.update(1 / 60);
  g.rig.mode = 'far'; g.rig.yawOff = 0.35;
  for (let i = 0; i < 30; i++) g.update(1 / 60);
  g.render(1 / 60);
  const info = { kmh: boat.phys.kmh, y: boat.y };
  window.__info = info;
  return g.canvas.toDataURL('image/jpeg', 0.9);
});
fs.writeFileSync('data/shots/wake2.jpg', Buffer.from(url.split(',')[1], 'base64'));
console.log(JSON.stringify(await page.evaluate(() => window.__info)));
console.log(logs.filter((l) => !/getImageData/.test(l)).slice(0, 10).join('\n') || 'no errors');
await close();
